### ISSUE TITLE
素材

### ISSUE THREAD

**Issue by YanQinYuan** [Ashleytl/AIWriter005BP#4]
有趣的素材往这里丢！

**Comment by YanQinYuan** [comment]
[给台阶照片添加萌萌的涂鸦图案](http://www.missyuan.com/thread-739944-1-1.html)

**Comment by April529** [comment]
[ 洞穴画资料](https://shimo.im/docs/uIOpSaOXaOoX5hVs)

**Comment by YanQinYuan** [comment]
分享一些设计类课程的素材
[Design school](https://www.zhihu.com/question/21481878)
[少年设计思维班](https://www.youthmba.com/course/explore?classifyCode=designCollege)

David：“设计”这个词是一个非常有趣的词。在人们的脑子里，都会认为设计是设计一种东西，例如我是一名雕塑设计师。还有很多时候人们说：“Oh，我是一个设计师”，我们会问：“你设计什么？设计衣服？设计汽车？”，所以他们说的都是设计一个东西。而不是一个方法论。但是现实中，我们都在一直都在设计，所以我们决定把名字叫做《设计思维》，这并不意味我们必须是艺术家，时尚达人，或者是一种身份象征。我们指的是观点、想法ideas.
例如，如何使人们做火车的时候心情更加愉快，或者enjoy
their lunch more。所以者并不一定要是设计师。    所以创立设计思维就是要推动只是局限在对一个东西的具体设计、只是艺术家的责任转变到一种设计的思维方法。这更像是一种科学的方法scientific
method。科学的方法就像是收集数据，对数据进行分析，然后得出结论。设计思维也是如此：是一种了解别人的想法、愿望，然后实现一种方法，帮助他们。所以设计思维并不是新的概念，这是一种方法，让你学会设计师是怎么想的。
