### ISSUE TITLE
起个性感名字

### ISSUE THREAD

**Issue by YanQinYuan** [Ashleytl/AIWriter005BP#8]
- 阳老的意见：

名称最好选择具象、进化早期的词汇，可以不与女性相关。
具象：橘子；蝴蝶
早期：星辰、大海
隐喻（凋寒教练几次提到先从隐喻入手，我猜这是教练的秘笈。。。。）

红色（凋寒组长作品）
写作花园（欣怡教练作品）
二期三期名字整理

二期

陪孩子读诗
真卿造字
乐言
你宠我宠
蝴蝶社区

三期

写作花园
蝶梦
红色
昼行夜梦
趣写
星辰小王子
- 总结

名词（一般采用隐喻方式）
完全名词组合：星辰小王子；红色；蝴蝶社区
形容词+动词
乐言； 趣写
主谓结构
真卿造字；你宠我宠
其他
陪孩子读诗；昼行夜梦

- 建议：
可以挖掘 **洞穴**，**原始人用壁画记录生活**等意象，取一个性感的名字

**Comment by Ashleytl** [comment]
我在这里罗列了一些名字，你们也搬上你们的，然后一起选定一个。

Color the City 

- 动宾结构
绘世界／彩色城市／绘城市之光／筑城市之光

- 隐喻空间
家／你家我家／家园
以家隐喻为城市，家里小空间，外面大空间。

- 瞎想的
耕成（耕城）／耕成间（耕城间）
意一起耕种城市，这里的成与城谐音，同时寓意成果。

待持续添加

**Comment by Ashleytl** [comment]
在BETTERNAME上面，用“涂鸦”作关键词，搜出以下有趣名字
http://name.aiwriter.cn/

> 无名涂鸦/慎言涂鸦/于乐涂鸦/十朋涂鸦
仁以涂鸦/怡如涂鸦/泡黄涂鸦/黄枪涂鸦/使红涂鸦

个人喜欢第一组的名字

**Comment by April529** [comment]
图雅  
上色厝  
更城  
胡同画手  
......

**Comment by April529** [comment]
新撰组
流光组
溢彩组

**Comment by April529** [comment]
转置空间
置换空间
交换空间（央视栏目）
